# Generated by Django 5.1.6 on 2025-02-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(max_length=200, verbose_name="Название продукта"),
                ),
                ("type", models.CharField(max_length=3, verbose_name="Тип")),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата выпуска"
                    ),
                ),
                (
                    "foundry",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Производитель (Foundry)",
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Бренд (Vendor)",
                    ),
                ),
                (
                    "process_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Техпроцесс (нм)"
                    ),
                ),
                (
                    "tdp",
                    models.IntegerField(blank=True, null=True, verbose_name="TDP (Вт)"),
                ),
                (
                    "die_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Размер кристалла (мм²)",
                    ),
                ),
                (
                    "transistors",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Транзисторы (млн)"
                    ),
                ),
                (
                    "freq",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Частота (МГц)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Процессор",
                "verbose_name_plural": "Процессоры",
                "db_table": "cpus_products",
            },
        ),
    ]
