# Generated by Django 5.1.6 on 2025-02-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fp16_gflops",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="FP16 GFLOPS",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fp32_gflops",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="FP32 GFLOPS",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fp64_gflops",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="FP64 GFLOPS",
            ),
        ),
    ]
