# Generated by Django 5.1.6 on 2025-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(max_length=200, verbose_name="Название продукта"),
                ),
                ("type", models.CharField(max_length=3, verbose_name="Тип")),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата выпуска"
                    ),
                ),
            ],
            options={
                "verbose_name": "Процессор",
                "verbose_name_plural": "Процессоры",
                "db_table": "cpus",
            },
        ),
    ]
