# Generated by Django 5.1.6 on 2025-02-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="die_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Размер кристалла (мм²)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="foundry",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Производитель (Foundry)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="freq",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Частота (МГц)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="process_size",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Техпроцесс (нм)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tdp",
            field=models.IntegerField(blank=True, null=True, verbose_name="TDP (Вт)"),
        ),
        migrations.AddField(
            model_name="product",
            name="transistors",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Транзисторы (млн)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="vendor",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Бренд (Vendor)"
            ),
        ),
    ]
